install.packages("janitor")
install.packages("kimisc")
install.packages("openxlsx")
library("tidyverse")
library("dplyr")
library("janitor")
library("lubridate")
library("readxl")
library("openxlsx")
library("pivottabler")
Mode <- function(x){
  ux <- unique(x)
  ux[which.max(tabulate(match(x,ux)))]
}
df <- read_excel("Assignment_Revenue&Exchanges.xlsx")
str(df)
df <- rename_with(df,tolower)
df <- clean_names(df)
df$city <- tolower(df$city)
df$ship_state <- tolower(df$ship_state)
unique(df$orderdate[order(df$orderdate)])
df$order_qty <- as.numeric(df$order_qty)
df$new <- month(df$orderdate)
glimpse(df)
df <- filter(df, status!="Cancelled" & status!= "Shipped & Returned")
pt1 <- PivotTable$new()
pt1$addData(df[order(df$new, decreasing=F),])
pt1$addRowDataGroups("city")
#pt1$addRowDataGroups("new")
pt1$defineCalculation(calculationName="Total Orders",summariseExpression = "sum(order_qty)")
#pt1$defineCalculation(calculationName="Total Sales",summariseExpression = "sum(order_amount)")
pt1$sortRowDataGroups()
pt1$renderPivot()

df1 <- df %>%
  filter(new == 8)

Mode(df1$sku)
filter(df1,sku=="NM-SL-GR-8")
unique(df$sku)

pt2 <- PivotTable$new()
pt2$addData(df[order(df$new, decreasing=F),])
pt2$addRowDataGroups("sku")
pt2$addColumnDataGroups("new")
pt2$defineCalculation(calculationName="Total Orders",summariseExpression = "sum(order_qty)")
#pt2$defineCalculation(calculationName="Total Sales",summariseExpression = "sum(order_amount)")
pt2$evaluatePivot()
wb <- createWorkbook(creator = Sys.getenv("USERNAME"))
addWorksheet(wb, "Data")
pt2$writeToExcelWorksheet(wb=wb,wsName="Data",topRowNumber = 1, leftMostColumnNumber = 1, applyStyles=F)
saveWorkbook(wb, file="Inventory.xlsx",overwrite=TRUE)
#pt1$sortRowDataGroups()

unique(df$product_type)
filter(df,is.na(product_type))
df3 <- df %>%
  filter(new==10) %>%
  group_by(product_type)
summarise(df3, n())

pt3 <- PivotTable$new()
pt3$addData(df[order(df$new, decreasing=F),])
pt3$addRowDataGroups("product_type")
pt3$addColumnDataGroups("new")
pt3$defineCalculation(calculationName="Orders",summariseExpression = "sum(order_qty)")
#pt3$defineCalculation(calculationName="Sales",summariseExpression = "sum(order_amount)")
pt3$evaluatePivot()
wb <- createWorkbook(creator = Sys.getenv("USERNAME"))
addWorksheet(wb, "Data")
pt3$writeToExcelWorksheet(wb=wb,wsName="Data",topRowNumber = 1, leftMostColumnNumber = 1, applyStyles=F)
saveWorkbook(wb, file="Type_orders.xlsx",overwrite=TRUE)
#pt1$sortRowDataGroups()

